// Generated by CoffeeScript 1.4.0
(function() {
  var checkpanel, choisir_exo, membre, solution, _ref;

  _ref = [0, 0], membre = _ref[0], solution = _ref[1];

  choisir_exo = function(id, output) {
    var exo, text;
    $(".carte").remove();
    exo = $("" + id);
    membre = exo.data("membre");
    solution = exo.data("solution");
    text = exo.text().replace(/#([0-9]*\??)/g, "<div class='carte diese'>$1</div>").replace(/\$([0-9]*\??)/g, "<div class='carte dollar'>$1</div>").replace(/@([0-9]*\??)/g, "<div class='carte arobas'>$1</div>");
    $("" + output).empty().append("<div class='enonce'>" + text + "</div>").dialog({
      position: {
        my: 'right bottom',
        at: 'right bottom',
        of: '#panel'
      }
    });
    if ($("#panel").hasClass("rotate")) {
      $("" + output).dialog({
        width: $(window).width() * 1,
        height: $(window).height() * 0.3
      });
    } else {
      $("" + output).dialog({
        width: $(window).width() * 0.25,
        height: $(window).height() * 1
      });
    }
    return $(".carte").draggable({
      revert: "invalid",
      helper: "clone",
      appendTo: "#panel"
    });
  };

  checkpanel = function() {
    var b, dollar_en_haut, somme, t;
    somme = function(panel, classe) {
      var s, selector;
      s = 0;
      selector = "" + panel + " > " + classe;
      $(selector).each(function() {
        return s += $(this).data("valeur");
      });
      return s;
    };
    dollar_en_haut = $('#panel_top div:first-child').hasClass("dollar");
    if (dollar_en_haut) {
      t = somme("#panel_top", ".dollar");
      b = somme("#panel_bottom", ".diese");
    } else {
      t = somme("#panel_top", ".diese");
      b = somme("#panel_bottom", ".dollar");
    }
    if (t === b && b === membre && $(".arobas.carte_panel").length === 0) {
      return alert("bravo !");
    } else {
      return alert("Essayes encore !");
    }
  };

  $(function() {
    $(".exercice").each(function() {
      var html, id;
      id = $(this).attr("id");
      html = "<option value='" + id + "'>" + id + "</option>";
      return $("#exercices").append(html);
    });
    $("#exercices").selectmenu({
      select: function(event, data) {
        return choisir_exo("#" + data.item.value, "#enonce");
      }
    });
    $("#select_opener").click(function() {
      return $("#exercices").selectmenu("open");
    });
    $("#parametres").dialog({
      autoOpen: false
    });
    $("#menu_parametres").click(function() {
      if ($(" #parametres").dialog("isOpen")) {
        return $("#parametres").dialog("close");
      } else {
        return $("#parametres").dialog("open");
      }
    });
    $(' #checkbox_aide ').change(function() {
      if ($(this).is(":checked")) {
        return $(".carte_panel").addClass("aide");
      } else {
        return $(".carte_panel").removeClass("aide");
      }
    });
    $(' #checkbox_piege ').change(function() {
      if ($(this).is(":checked")) {
        return $(".arobas").addClass("carte").draggable('enable');
      } else {
        $(".arobas.carte_panel").remove();
        return $(".arobas").draggable('disable').removeClass("carte");
      }
    });
    $(' #checkbox_rotate ').change(function() {
      if ($(this).is(":checked")) {
        return $("#panel, #panel_top, #panel_bottom").addClass("rotate");
      } else {
        return $("#panel, #panel_top, #panel_bottom").removeClass("rotate");
      }
    });
    $('#trash').droppable({
      accept: ".carte_panel",
      greedy: true,
      activeClass: "trash-hover",
      hoverClass: "trash-active",
      drop: function(event, ui) {
        event.stopPropagation();
        return ui.draggable.remove();
      },
      over: function(event, ui) {
        return ui.draggable.addClass("remove").removeClass("carte");
      },
      out: function(event, ui) {
        return ui.draggable.addClass("carte").removeClass("remove");
      }
    });
    $('#panel_top, #panel_bottom').droppable({
      accept: ".carte",
      activeClass: "panel-hover",
      hoverClass: "panel-active",
      drop: function(event, ui) {
        var leClone, positionneBien, valeur,
          _this = this;
        positionneBien = function(unDraggable) {
          $(_this).append(unDraggable);
          if (!unDraggable.hasClass("carte_panel")) {
            return unDraggable.css({
              left: event.clientX - unDraggable.width() - $(_this).position().left,
              top: event.clientY - unDraggable.height()
            });
          } else {
            return unDraggable.css({
              left: event.clientX - unDraggable.width() / 2 - $(_this).position().left,
              top: event.clientY - unDraggable.height() / 2
            });
          }
        };
        if (ui.draggable.hasClass("carte_panel")) {
          return positionneBien($(ui.draggable));
        } else {
          leClone = ui.draggable.clone();
          positionneBien(leClone);
          valeur = parseInt(leClone.html());
          valeur = isNaN(valeur) ? solution : valeur;
          leClone.addClass("carte_panel").data("valeur", valeur);
          if ($("#checkbox_aide").is(":checked")) {
            $(leClone).addClass("aide");
          }
          return $(leClone).draggable({
            revert: "invalid",
            cursor: "move"
          });
        }
      }
    });
    return $('#check').click(function() {
      return checkpanel();
    });
  });

}).call(this);
